#common
block=block
item=item
creative_mode_tab=item_group
entity=entity
entity_type=entity_type
properties=settings
block_set_type=block_set_type
wood_type=wood_type
sound_type=block_sound_group
armor_material=armor_material
drops=loot_table
has_drops=has_drops
description=translation_key
required_features=required_features

#block
block.map_color=map_color
block.map_color_provider=map_color_provider
block.collision=collidable
block.sound=sound_group
block.light_level=luminance
block.explosion_resistance=resistance
block.destroy_time=hardness
block.strength=strength
block.requires_tool=tool_required
block.instabreak=instant_break
block.random_ticks=random_ticks
block.friction=slipperiness
block.speed_factor=velocity_multiplier
block.jump_factor=jump_velocity_multiplier
block.drops_like=drops_like
block.occlusion=opaque
block.air=is_air
block.ignited_by_lava=burnable
block.liquid=liquid
block.force_solid=force_solid
block.push_reaction=piston_behavior
block.terrain_particles=block_break_particles
block.instrument=instrument
block.replaceable=replaceable
block.valid_spawn=allows_spawning_predicate
block.redstone_conductor=solid_block_predicate
block.suffocating=suffocation_predicate
block.view_blocking=block_vision_predicate
block.post_process=post_process_predicate
block.emissive_rendering=emissive_lighting_predicate
block.dynamic_shape=dynamic_bounds
block.offset=offsetter

#block_sound_group
sound_type.empty=intentionally_empty
sound_type.wood=wood
sound_type.gravel=gravel
sound_type.grass=grass
sound_type.lily_pad=lily_pad
sound_type.stone=stone
sound_type.metal=metal
sound_type.glass=glass
sound_type.wool=wool
sound_type.sand=sand
sound_type.snow=snow
sound_type.powder_snow=powder_snow
sound_type.ladder=ladder
sound_type.anvil=anvil
sound_type.slime=slime
sound_type.honey=honey
sound_type.wet_grass=wet_grass
sound_type.coral=coral
sound_type.bamboo=bamboo
sound_type.bamboo_sapling=bamboo_sapling
sound_type.scaffolding=scaffolding
sound_type.sweet_berry_bush=sweet_berry_bush
sound_type.crop=crop
sound_type.hard_crop=stem
sound_type.vine=vine
sound_type.nether_wart=nether_wart
sound_type.lantern=lantern
sound_type.nylium=nylium
sound_type.fungus=fungus
sound_type.roots=roots
sound_type.shroomlight=shroomlight
sound_type.weeping_vines=weeping_vines
sound_type.twisting_vines=weeping_vines_low_pitch
sound_type.soul_sand=soul_sand
sound_type.soul_soil=soul_soil
sound_type.basalt=basalt
sound_type.wart=wart_block
sound_type.netherrack=netherrack
sound_type.nether_bricks=nether_bricks
sound_type.nether_sprouts=nether_sprouts
sound_type.nether_ore=nether_ore
sound_type.bone=bone
sound_type.netherite=netherite
sound_type.ancient_debris=ancient_debris
sound_type.lodestone=lodestone
sound_type.chain=chain
sound_type.nether_gold_ore=nether_gold_ore
sound_type.gilded_blackstone=gilded_blackstone
sound_type.candle=candle
sound_type.amethyst=amethyst_block
sound_type.amethyst_cluster=amethyst_cluster
sound_type.small_amethyst_bud=small_amethyst_bud
sound_type.medium_amethyst_bud=medium_amethyst_bud
sound_type.large_amethyst_bud=large_amethyst_bud
sound_type.tuff=tuff
sound_type.tuff_bricks=tuff_bricks
sound_type.polished_tuff=polished_tuff
sound_type.calcite=calcite
sound_type.dripstone=dripstone_block
sound_type.pointed_dripstone=pointed_dripstone
sound_type.copper=copper
sound_type.copper_bulb=copper_bulb
sound_type.copper_grate=copper_grate
sound_type.cave_vines=cave_vines
sound_type.spore_blossom=spore_blossom
sound_type.cactus_flower=cactus_flower
sound_type.azalea=azalea
sound_type.flowering_azalea=flowering_azalea
sound_type.moss_carpet=moss_carpet
sound_type.flowerbed=flowerbed
sound_type.leaf_litter=leaf_litter
sound_type.moss=moss_block
sound_type.big_dripleaf=big_dripleaf
sound_type.small_dripleaf=small_dripleaf
sound_type.rooted_dirt=rooted_dirt
sound_type.hanging_roots=hanging_roots
sound_type.azalea_leaves=azalea_leaves
sound_type.sculk_sensor=sculk_sensor
sound_type.sculk_catalyst=sculk_catalyst
sound_type.sculk=sculk
sound_type.sculk_vein=sculk_vein
sound_type.sculk_shrieker=sculk_shrieker
sound_type.glow_lichen=glow_lichen
sound_type.deepslate=deepslate
sound_type.deepslate_bricks=deepslate_bricks
sound_type.deepslate_tiles=deepslate_tiles
sound_type.polished_deepslate=polished_deepslate
sound_type.froglight=froglight
sound_type.frogspawn=frogspawn
sound_type.mangrove_roots=mangrove_roots
sound_type.muddy_mangrove_roots=muddy_mangrove_roots
sound_type.mud=mud
sound_type.mud_bricks=mud_bricks
sound_type.packed_mud=packed_mud
sound_type.hanging_sign=hanging_sign
sound_type.nether_wood_hanging_sign=nether_wood_hanging_sign
sound_type.bamboo_wood_hanging_sign=bamboo_wood_hanging_sign
sound_type.bamboo_wood=bamboo_wood
sound_type.nether_wood=nether_wood
sound_type.cherry_wood=cherry_wood
sound_type.cherry_sapling=cherry_sapling
sound_type.cherry_leaves=cherry_leaves
sound_type.cherry_wood_hanging_sign=cherry_wood_hanging_sign
sound_type.chiseled_bookshelf=chiseled_bookshelf
sound_type.suspicious_sand=suspicious_sand
sound_type.suspicious_gravel=suspicious_gravel
sound_type.decorated_pot=decorated_pot
sound_type.decorated_pot_cracked=decorated_pot_shatter
sound_type.trial_spawner=trial_spawner
sound_type.sponge=sponge
sound_type.wet_sponge=wet_sponge
sound_type.vault=vault
sound_type.creaking_heart=creaking_heart
sound_type.heavy_core=heavy_core
sound_type.cobweb=cobweb
sound_type.spawner=spawner
sound_type.resin=resin
sound_type.resin_bricks=resin_bricks
sound_type.iron=iron
sound_type.dried_ghast=dried_ghast

#sapling_generator
tree_grower.secondary_chance=rare_chance
tree_grower.mega_tree=mega_variant
tree_grower.secondary_mega_tree=rare_mega_variant
tree_grower.tree=regular_variant
tree_grower.secondary_tree=rare_regular_variant
tree_grower.flowers=bees_variant
tree_grower.secondary_flowers=rare_bees_variant

#item_type
item_type.air=air_block
item_type.armor_stand=armor_stand
item_type.arrow=arrow
item_type.axe=axe
item_type.banner=banner
item_type.bed=bed
item_type.block=block
item_type.boat=boat
item_type.bone_meal=bone_meal
item_type.bow=bow
item_type.brush=brush
item_type.bucket=bucket
item_type.bundle=bundle
item_type.compass=compass
item_type.crossbow=crossbow
item_type.debug_stick=debug_stick
item_type.hanging_entity=decoration
item_type.disc_fragment=disc_fragment
item_type.dye=dye
item_type.egg=egg
item_type.empty_map=empty_map
item_type.end_crystal=end_crystal
item_type.ender_eye=ender_eye
item_type.enderpearl=ender_pearl
item_type.mob_bucket=entity_bucket
item_type.experience_bottle=experience_bottle
item_type.map=filled_map
item_type.fire_charge=fire_charge
item_type.firework_rocket=firework_rocket
item_type.fishing_rod=fishing_rod
item_type.flint_and_steel=flint_and_steel
item_type.bottle=glass_bottle
item_type.glow_ink_sac=glow_ink_sac
item_type.instrument=goat_horn
item_type.hanging_sign=hanging_sign
item_type.hoe=hoe
item_type.honeycomb=honeycomb
item_type.ink_sac=ink_sac
item_type.item_frame=item_frame
item_type.knowledge_book=knowledge_book
item_type.lead=lead
item_type.lingering_potion=lingering_potion
item_type.mace=mace
item_type.minecart=minecart
item_type.name_tag=name_tag
item_type.food_on_a_stick=on_a_stick
item_type.game_master_block=operator_only_block
item_type.place_on_water_block=place_on_water_block
item_type.player_head=player_head
item_type.potion=potion
item_type.solid_bucket=powder_snow_bucket
item_type.scaffolding_block=scaffolding
item_type.shears=shears
item_type.shield=shield
item_type.shovel=shovel
item_type.sign=sign
item_type.smithing_template=smithing_template
item_type.snowball=snowball
item_type.spawn_egg=spawn_egg
item_type.spectral_arrow=spectral_arrow
item_type.splash_potion=splash_potion
item_type.spyglass=spyglass
item_type.double_high_block=tall_block
item_type.tipped_arrow=tipped_arrow
item_type.trident=trident
item_type.standing_and_wall_block=vertically_attachable_block
item_type.wind_charge=wind_charge
item_type.writable_book=writable_book
item_type.written_book=written_book

#item_group
creative_mode_tab.title=display_name
creative_mode_tab.display_items=display_stacks
creative_mode_tab.show_title=should_render_name

#tool_material/armor_material
material.enchantability=enchantment_value

#entity_type
entity_type.category=spawn_group
entity_type.serialize=saveable
entity_type.summon=summonable
entity_type.fire_immune=fire_immune
entity_type.can_spawn_far=spawnable_far_from_player
entity_type.immune_to=can_spawn_inside
entity_type.dimensions=dimensions
entity_type.spawn_dimensions_scale=spawn_box_scale
entity_type.client_tracking_range=max_track_distance
entity_type.update_interval=track_tick_interval