package mod.moineau.contentpacks.registry;

import com.google.common.base.Suppliers;
import com.mojang.datafixers.util.Function3;
import com.mojang.serialization.DataResult;
import com.mojang.serialization.MapCodec;
import mod.moineau.contentpacks.api.util.FunctionUtil;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ambient.Bat;
import net.minecraft.world.entity.animal.allay.Allay;
import net.minecraft.world.entity.animal.armadillo.Armadillo;
import net.minecraft.world.entity.animal.axolotl.Axolotl;
import net.minecraft.world.entity.animal.bee.Bee;
import net.minecraft.world.entity.animal.camel.Camel;
import net.minecraft.world.entity.animal.camel.CamelHusk;
import net.minecraft.world.entity.animal.chicken.Chicken;
import net.minecraft.world.entity.animal.cow.Cow;
import net.minecraft.world.entity.animal.cow.MushroomCow;
import net.minecraft.world.entity.animal.dolphin.Dolphin;
import net.minecraft.world.entity.animal.equine.*;
import net.minecraft.world.entity.animal.feline.Cat;
import net.minecraft.world.entity.animal.feline.Ocelot;
import net.minecraft.world.entity.animal.fish.Cod;
import net.minecraft.world.entity.animal.fish.Pufferfish;
import net.minecraft.world.entity.animal.fish.Salmon;
import net.minecraft.world.entity.animal.fish.TropicalFish;
import net.minecraft.world.entity.animal.fox.Fox;
import net.minecraft.world.entity.animal.frog.Frog;
import net.minecraft.world.entity.animal.frog.Tadpole;
import net.minecraft.world.entity.animal.goat.Goat;
import net.minecraft.world.entity.animal.golem.CopperGolem;
import net.minecraft.world.entity.animal.golem.IronGolem;
import net.minecraft.world.entity.animal.golem.SnowGolem;
import net.minecraft.world.entity.animal.happyghast.HappyGhast;
import net.minecraft.world.entity.animal.nautilus.Nautilus;
import net.minecraft.world.entity.animal.nautilus.ZombieNautilus;
import net.minecraft.world.entity.animal.panda.Panda;
import net.minecraft.world.entity.animal.parrot.Parrot;
import net.minecraft.world.entity.animal.pig.Pig;
import net.minecraft.world.entity.animal.polarbear.PolarBear;
import net.minecraft.world.entity.animal.rabbit.Rabbit;
import net.minecraft.world.entity.animal.sheep.Sheep;
import net.minecraft.world.entity.animal.sniffer.Sniffer;
import net.minecraft.world.entity.animal.squid.GlowSquid;
import net.minecraft.world.entity.animal.squid.Squid;
import net.minecraft.world.entity.animal.turtle.Turtle;
import net.minecraft.world.entity.animal.wolf.Wolf;
import net.minecraft.world.entity.boss.enderdragon.EndCrystal;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;
import net.minecraft.world.entity.boss.wither.WitherBoss;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.entity.decoration.GlowItemFrame;
import net.minecraft.world.entity.decoration.ItemFrame;
import net.minecraft.world.entity.decoration.LeashFenceKnotEntity;
import net.minecraft.world.entity.decoration.painting.Painting;
import net.minecraft.world.entity.item.FallingBlockEntity;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.item.PrimedTnt;
import net.minecraft.world.entity.monster.*;
import net.minecraft.world.entity.monster.breeze.Breeze;
import net.minecraft.world.entity.monster.creaking.Creaking;
import net.minecraft.world.entity.monster.cubemob.MagmaCube;
import net.minecraft.world.entity.monster.cubemob.Slime;
import net.minecraft.world.entity.monster.cubemob.SulfurCube;
import net.minecraft.world.entity.monster.hoglin.Hoglin;
import net.minecraft.world.entity.monster.illager.Evoker;
import net.minecraft.world.entity.monster.illager.Illusioner;
import net.minecraft.world.entity.monster.illager.Pillager;
import net.minecraft.world.entity.monster.illager.Vindicator;
import net.minecraft.world.entity.monster.piglin.Piglin;
import net.minecraft.world.entity.monster.piglin.PiglinBrute;
import net.minecraft.world.entity.monster.skeleton.*;
import net.minecraft.world.entity.monster.spider.CaveSpider;
import net.minecraft.world.entity.monster.spider.Spider;
import net.minecraft.world.entity.monster.warden.Warden;
import net.minecraft.world.entity.monster.zombie.*;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.entity.npc.wanderingtrader.WanderingTrader;
import net.minecraft.world.entity.projectile.*;
import net.minecraft.world.entity.projectile.arrow.Arrow;
import net.minecraft.world.entity.projectile.arrow.SpectralArrow;
import net.minecraft.world.entity.projectile.arrow.ThrownTrident;
import net.minecraft.world.entity.projectile.hurtingprojectile.DragonFireball;
import net.minecraft.world.entity.projectile.hurtingprojectile.LargeFireball;
import net.minecraft.world.entity.projectile.hurtingprojectile.SmallFireball;
import net.minecraft.world.entity.projectile.hurtingprojectile.WitherSkull;
import net.minecraft.world.entity.projectile.hurtingprojectile.windcharge.BreezeWindCharge;
import net.minecraft.world.entity.projectile.hurtingprojectile.windcharge.WindCharge;
import net.minecraft.world.entity.projectile.throwableitemprojectile.*;
import net.minecraft.world.entity.vehicle.boat.Boat;
import net.minecraft.world.entity.vehicle.boat.ChestBoat;
import net.minecraft.world.entity.vehicle.boat.Raft;
import net.minecraft.world.entity.vehicle.minecart.*;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.Level;

import java.util.function.Supplier;

public class VanillaEntityFactories {
    public static void initialize(Registry<MapCodec<? extends EntityType.EntityFactory<?>>> registry) {
        Registry.register(registry, Identifier.withDefaultNamespace("allay"), of(Allay::new));
        Registry.register(registry, Identifier.withDefaultNamespace("area_effect_cloud"), VanillaEntityFactories.<AreaEffectCloud>of(AreaEffectCloud::new));
        Registry.register(registry, Identifier.withDefaultNamespace("armadillo"), of(Armadillo::new));
        Registry.register(registry, Identifier.withDefaultNamespace("armor_stand"), VanillaEntityFactories.<ArmorStand>of(ArmorStand::new));
        Registry.register(registry, Identifier.withDefaultNamespace("arrow"), VanillaEntityFactories.<Arrow>of(Arrow::new));
        Registry.register(registry, Identifier.withDefaultNamespace("axolotl"), of(Axolotl::new));
        Registry.register(registry, Identifier.withDefaultNamespace("bat"), of(Bat::new));
        Registry.register(registry, Identifier.withDefaultNamespace("bee"), of(Bee::new));
        Registry.register(registry, Identifier.withDefaultNamespace("blaze"), of(Blaze::new));
        Registry.register(registry, Identifier.withDefaultNamespace("block_display"), of(Display.BlockDisplay::new));
        Registry.register(registry, Identifier.withDefaultNamespace("bogged"), of(Bogged::new));
        Registry.register(registry, Identifier.withDefaultNamespace("breeze"), of(Breeze::new));
        Registry.register(registry, Identifier.withDefaultNamespace("breeze_wind_charge"), VanillaEntityFactories.<BreezeWindCharge>of(BreezeWindCharge::new));
        Registry.register(registry, Identifier.withDefaultNamespace("camel"), of(Camel::new));
        Registry.register(registry, Identifier.withDefaultNamespace("camel_husk"), of(CamelHusk::new));
        Registry.register(registry, Identifier.withDefaultNamespace("cat"), of(Cat::new));
        Registry.register(registry, Identifier.withDefaultNamespace("cave_spider"), of(CaveSpider::new));
        Registry.register(registry, Identifier.withDefaultNamespace("minecart_chest"), of(MinecartChest::new));
        Registry.register(registry, Identifier.withDefaultNamespace("chicken"), of(Chicken::new));
        Registry.register(registry, Identifier.withDefaultNamespace("cod"), of(Cod::new));
        Registry.register(registry, Identifier.withDefaultNamespace("copper_golem"), of(CopperGolem::new));
        Registry.register(registry, Identifier.withDefaultNamespace("minecart_command_block"), of(MinecartCommandBlock::new));
        Registry.register(registry, Identifier.withDefaultNamespace("cow"), of(Cow::new));
        Registry.register(registry, Identifier.withDefaultNamespace("creaking"), of(Creaking::new));
        Registry.register(registry, Identifier.withDefaultNamespace("creeper"), of(Creeper::new));
        Registry.register(registry, Identifier.withDefaultNamespace("dolphin"), of(Dolphin::new));
        Registry.register(registry, Identifier.withDefaultNamespace("donkey"), of(Donkey::new));
        Registry.register(registry, Identifier.withDefaultNamespace("dragon_fireball"), VanillaEntityFactories.<DragonFireball>of(DragonFireball::new));
        Registry.register(registry, Identifier.withDefaultNamespace("drowned"), of(Drowned::new));
        Registry.register(registry, Identifier.withDefaultNamespace("thrown_egg"), VanillaEntityFactories.<ThrownEgg>of(ThrownEgg::new));
        Registry.register(registry, Identifier.withDefaultNamespace("elder_guardian"), of(ElderGuardian::new));
        Registry.register(registry, Identifier.withDefaultNamespace("ender_man"), of(EnderMan::new));
        Registry.register(registry, Identifier.withDefaultNamespace("endermite"), of(Endermite::new));
        Registry.register(registry, Identifier.withDefaultNamespace("ender_dragon"), of(EnderDragon::new));
        Registry.register(registry, Identifier.withDefaultNamespace("thrown_enderpearl"), VanillaEntityFactories.<ThrownEnderpearl>of(ThrownEnderpearl::new));
        Registry.register(registry, Identifier.withDefaultNamespace("end_crystal"), VanillaEntityFactories.<EndCrystal>of(EndCrystal::new));
        Registry.register(registry, Identifier.withDefaultNamespace("evoker"), of(Evoker::new));
        Registry.register(registry, Identifier.withDefaultNamespace("evoker_fangs"), VanillaEntityFactories.<EvokerFangs>of(EvokerFangs::new));
        Registry.register(registry, Identifier.withDefaultNamespace("thrown_experience_bottle"), VanillaEntityFactories.<ThrownExperienceBottle>of(ThrownExperienceBottle::new));
        Registry.register(registry, Identifier.withDefaultNamespace("experience_orb"), VanillaEntityFactories.<ExperienceOrb>of(ExperienceOrb::new));
        Registry.register(registry, Identifier.withDefaultNamespace("eye_of_ender"), VanillaEntityFactories.<EyeOfEnder>of(EyeOfEnder::new));
        Registry.register(registry, Identifier.withDefaultNamespace("falling_block_entity"), of(FallingBlockEntity::new));
        Registry.register(registry, Identifier.withDefaultNamespace("large_fireball"), VanillaEntityFactories.<LargeFireball>of(LargeFireball::new));
        Registry.register(registry, Identifier.withDefaultNamespace("firework_rocket_entity"), VanillaEntityFactories.<FireworkRocketEntity>of(FireworkRocketEntity::new));
        Registry.register(registry, Identifier.withDefaultNamespace("fox"), of(Fox::new));
        Registry.register(registry, Identifier.withDefaultNamespace("frog"), of(Frog::new));
        Registry.register(registry, Identifier.withDefaultNamespace("minecart_furnace"), of(MinecartFurnace::new));
        Registry.register(registry, Identifier.withDefaultNamespace("ghast"), of(Ghast::new));
        Registry.register(registry, Identifier.withDefaultNamespace("happy_ghast"), of(HappyGhast::new));
        Registry.register(registry, Identifier.withDefaultNamespace("giant"), of(Giant::new));
        Registry.register(registry, Identifier.withDefaultNamespace("glow_item_frame"), VanillaEntityFactories.<GlowItemFrame>of(GlowItemFrame::new));
        Registry.register(registry, Identifier.withDefaultNamespace("glow_squid"), of(GlowSquid::new));
        Registry.register(registry, Identifier.withDefaultNamespace("goat"), of(Goat::new));
        Registry.register(registry, Identifier.withDefaultNamespace("guardian"), of(Guardian::new));
        Registry.register(registry, Identifier.withDefaultNamespace("hoglin"), of(Hoglin::new));
        Registry.register(registry, Identifier.withDefaultNamespace("minecart_hopper"), of(MinecartHopper::new));
        Registry.register(registry, Identifier.withDefaultNamespace("horse"), of(Horse::new));
        Registry.register(registry, Identifier.withDefaultNamespace("husk"), of(Husk::new));
        Registry.register(registry, Identifier.withDefaultNamespace("illusioner"), of(Illusioner::new));
        Registry.register(registry, Identifier.withDefaultNamespace("interaction"), of(Interaction::new));
        Registry.register(registry, Identifier.withDefaultNamespace("iron_golem"), of(IronGolem::new));
        Registry.register(registry, Identifier.withDefaultNamespace("item_entity"), VanillaEntityFactories.<ItemEntity>of(ItemEntity::new));
        Registry.register(registry, Identifier.withDefaultNamespace("item_display"), of(Display.ItemDisplay::new));
        Registry.register(registry, Identifier.withDefaultNamespace("item_frame"), VanillaEntityFactories.<ItemFrame>of(ItemFrame::new));
        Registry.register(registry, Identifier.withDefaultNamespace("leash_fence_knot_entity"), VanillaEntityFactories.<LeashFenceKnotEntity>of(LeashFenceKnotEntity::new));
        Registry.register(registry, Identifier.withDefaultNamespace("lightning_bolt"), of(LightningBolt::new));
        Registry.register(registry, Identifier.withDefaultNamespace("llama"), of(Llama::new));
        Registry.register(registry, Identifier.withDefaultNamespace("llama_spit"), VanillaEntityFactories.<LlamaSpit>of(LlamaSpit::new));
        Registry.register(registry, Identifier.withDefaultNamespace("magma_cube"), of(MagmaCube::new));
        Registry.register(registry, Identifier.withDefaultNamespace("marker"), of(Marker::new));
        Registry.register(registry, Identifier.withDefaultNamespace("minecart"), of(Minecart::new));
        Registry.register(registry, Identifier.withDefaultNamespace("mushroom_cow"), of(MushroomCow::new));
        Registry.register(registry, Identifier.withDefaultNamespace("mule"), of(Mule::new));
        Registry.register(registry, Identifier.withDefaultNamespace("nautilus"), of(Nautilus::new));
        Registry.register(registry, Identifier.withDefaultNamespace("ocelot"), of(Ocelot::new));
        Registry.register(registry, Identifier.withDefaultNamespace("ominous_item_spawner"), of(OminousItemSpawner::new));
        Registry.register(registry, Identifier.withDefaultNamespace("painting"), VanillaEntityFactories.<Painting>of(Painting::new));
        Registry.register(registry, Identifier.withDefaultNamespace("panda"), of(Panda::new));
        Registry.register(registry, Identifier.withDefaultNamespace("parched"), of(Parched::new));
        Registry.register(registry, Identifier.withDefaultNamespace("parrot"), of(Parrot::new));
        Registry.register(registry, Identifier.withDefaultNamespace("phantom"), of(Phantom::new));
        Registry.register(registry, Identifier.withDefaultNamespace("pig"), of(Pig::new));
        Registry.register(registry, Identifier.withDefaultNamespace("piglin"), of(Piglin::new));
        Registry.register(registry, Identifier.withDefaultNamespace("piglin_brute"), of(PiglinBrute::new));
        Registry.register(registry, Identifier.withDefaultNamespace("pillager"), of(Pillager::new));
        Registry.register(registry, Identifier.withDefaultNamespace("polar_bear"), of(PolarBear::new));
        Registry.register(registry, Identifier.withDefaultNamespace("thrown_splash_potion"), VanillaEntityFactories.<ThrownSplashPotion>of(ThrownSplashPotion::new));
        Registry.register(registry, Identifier.withDefaultNamespace("thrown_lingering_potion"), VanillaEntityFactories.<ThrownLingeringPotion>of(ThrownLingeringPotion::new));
        Registry.register(registry, Identifier.withDefaultNamespace("pufferfish"), of(Pufferfish::new));
        Registry.register(registry, Identifier.withDefaultNamespace("rabbit"), of(Rabbit::new));
        Registry.register(registry, Identifier.withDefaultNamespace("ravager"), of(Ravager::new));
        Registry.register(registry, Identifier.withDefaultNamespace("salmon"), of(Salmon::new));
        Registry.register(registry, Identifier.withDefaultNamespace("sheep"), of(Sheep::new));
        Registry.register(registry, Identifier.withDefaultNamespace("shulker"), of(Shulker::new));
        Registry.register(registry, Identifier.withDefaultNamespace("shulker_bullet"), VanillaEntityFactories.<ShulkerBullet>of(ShulkerBullet::new));
        Registry.register(registry, Identifier.withDefaultNamespace("silverfish"), of(Silverfish::new));
        Registry.register(registry, Identifier.withDefaultNamespace("skeleton"), of(Skeleton::new));
        Registry.register(registry, Identifier.withDefaultNamespace("skeleton_horse"), of(SkeletonHorse::new));
        Registry.register(registry, Identifier.withDefaultNamespace("slime"), of(Slime::new));
        Registry.register(registry, Identifier.withDefaultNamespace("small_fireball"), VanillaEntityFactories.<SmallFireball>of(SmallFireball::new));
        Registry.register(registry, Identifier.withDefaultNamespace("sniffer"), of(Sniffer::new));
        Registry.register(registry, Identifier.withDefaultNamespace("snowball"), VanillaEntityFactories.<Snowball>of(Snowball::new));
        Registry.register(registry, Identifier.withDefaultNamespace("snow_golem"), of(SnowGolem::new));
        Registry.register(registry, Identifier.withDefaultNamespace("minecart_spawner"), of(MinecartSpawner::new));
        Registry.register(registry, Identifier.withDefaultNamespace("spectral_arrow"), VanillaEntityFactories.<SpectralArrow>of(SpectralArrow::new));
        Registry.register(registry, Identifier.withDefaultNamespace("spider"), of(Spider::new));
        Registry.register(registry, Identifier.withDefaultNamespace("squid"), of(Squid::new));
        Registry.register(registry, Identifier.withDefaultNamespace("stray"), of(Stray::new));
        Registry.register(registry, Identifier.withDefaultNamespace("strider"), of(Strider::new));
        Registry.register(registry, Identifier.withDefaultNamespace("sulfur_cube"), of(SulfurCube::new));
        Registry.register(registry, Identifier.withDefaultNamespace("tadpole"), of(Tadpole::new));
        Registry.register(registry, Identifier.withDefaultNamespace("text_display"), of(Display.TextDisplay::new));
        Registry.register(registry, Identifier.withDefaultNamespace("primed_tnt"), VanillaEntityFactories.<PrimedTnt>of(PrimedTnt::new));
        Registry.register(registry, Identifier.withDefaultNamespace("minecart_tnt"), of(MinecartTNT::new));
        Registry.register(registry, Identifier.withDefaultNamespace("trader_llama"), of(TraderLlama::new));
        Registry.register(registry, Identifier.withDefaultNamespace("thrown_trident"), VanillaEntityFactories.<ThrownTrident>of(ThrownTrident::new));
        Registry.register(registry, Identifier.withDefaultNamespace("tropical_fish"), of(TropicalFish::new));
        Registry.register(registry, Identifier.withDefaultNamespace("turtle"), of(Turtle::new));
        Registry.register(registry, Identifier.withDefaultNamespace("vex"), of(Vex::new));
        Registry.register(registry, Identifier.withDefaultNamespace("villager"), of(Villager::new));
        Registry.register(registry, Identifier.withDefaultNamespace("vindicator"), of(Vindicator::new));
        Registry.register(registry, Identifier.withDefaultNamespace("wandering_trader"), of(WanderingTrader::new));
        Registry.register(registry, Identifier.withDefaultNamespace("warden"), of(Warden::new));
        Registry.register(registry, Identifier.withDefaultNamespace("wind_charge"), VanillaEntityFactories.<WindCharge>of(WindCharge::new));
        Registry.register(registry, Identifier.withDefaultNamespace("witch"), of(Witch::new));
        Registry.register(registry, Identifier.withDefaultNamespace("wither_boss"), of(WitherBoss::new));
        Registry.register(registry, Identifier.withDefaultNamespace("wither_skeleton"), of(WitherSkeleton::new));
        Registry.register(registry, Identifier.withDefaultNamespace("wither_skull"), VanillaEntityFactories.<WitherSkull>of(WitherSkull::new));
        Registry.register(registry, Identifier.withDefaultNamespace("wolf"), of(Wolf::new));
        Registry.register(registry, Identifier.withDefaultNamespace("zoglin"), of(Zoglin::new));
        Registry.register(registry, Identifier.withDefaultNamespace("zombie"), VanillaEntityFactories.<Zombie>of(Zombie::new));
        Registry.register(registry, Identifier.withDefaultNamespace("zombie_horse"), of(ZombieHorse::new));
        Registry.register(registry, Identifier.withDefaultNamespace("zombie_nautilus"), of(ZombieNautilus::new));
        Registry.register(registry, Identifier.withDefaultNamespace("zombie_villager"), of(ZombieVillager::new));
        Registry.register(registry, Identifier.withDefaultNamespace("zombified_piglin"), of(ZombifiedPiglin::new));
        Registry.register(registry, Identifier.withDefaultNamespace("fishing_hook"), VanillaEntityFactories.<FishingHook>of(FishingHook::new));
        Registry.register(registry, Identifier.withDefaultNamespace("boat"), boat(Boat::new));
        Registry.register(registry, Identifier.withDefaultNamespace("chest_boat"), boat(ChestBoat::new));
        Registry.register(registry, Identifier.withDefaultNamespace("raft"), boat(Raft::new));
        Registry.register(registry, Identifier.withDefaultNamespace("chest_raft"), boat(ChestBoat::new));
    }

    private static <T extends Entity> MapCodec<? extends EntityType.EntityFactory<?>> of(EntityType.EntityFactory<T> factory) {
        return MapCodec.unit(factory);
    }

    private static <T extends Entity> MapCodec<? extends EntityType.EntityFactory<?>> boat(Function3<EntityType<T>, Level, Supplier<Item>, Entity> factory) {
        return ResourceKey.codec(Registries.ITEM).<Supplier<Item>>flatComapMap(
                key -> Suppliers.memoize(() -> BuiltInRegistries.ITEM.getValue(key)),
                item -> BuiltInRegistries.ITEM.getResourceKey(item.get()).map(DataResult::success).orElseGet(() -> DataResult.error(() -> ""))
        ).<EntityType.EntityFactory<?>>xmap(
                item -> ((type, level) -> factory.apply((EntityType<T>) type, level, item)),
                FunctionUtil::nothing
        ).fieldOf("item");
    }
}
