package mod.moineau.contentpacks.client.render.entity;

import com.mojang.serialization.Codec;
import com.mojang.serialization.MapCodec;
import com.mojang.serialization.MapDecoder;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import mod.moineau.api.util.CodecUtil;
import mod.moineau.api.util.FunctionUtil;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.renderer.entity.*;
import net.minecraft.client.renderer.entity.player.AvatarRenderer;
import net.minecraft.client.renderer.entity.state.EntityRenderState;
import net.minecraft.resources.Identifier;
import net.minecraft.util.ExtraCodecs;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.monster.creaking.Creaking;
import net.minecraft.world.entity.monster.illager.SpellcasterIllager;

import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.function.Supplier;

public class EntityRendererTypes {
    public static final ExtraCodecs.LateBoundIdMapper<Identifier, MapCodec<? extends EntityRendererProvider<?>>> ID_MAPPER = new ExtraCodecs.LateBoundIdMapper<>();
    public static final MapCodec<EntityRendererProvider<?>> CODEC = ID_MAPPER.codec(Identifier.CODEC).dispatchMap(FunctionUtil::nothing, Function.identity());
    public static final Codec<ModelLayerLocation> MODEL_LAYER_LOCATION_CODEC = Codec.withAlternative(
            RecordCodecBuilder.create(instance -> instance.group(
                    Identifier.CODEC.fieldOf("id").forGetter(ModelLayerLocation::model),
                    Codec.STRING.fieldOf("layer").forGetter(ModelLayerLocation::layer)
            ).apply(instance, ModelLayerLocation::new)),
            Identifier.CODEC.xmap(id -> new ModelLayerLocation(id, "main"), ModelLayerLocation::model)
    );
//    public static final MapCodec<? extends EntityRendererProvider<?>> BANNER = of(BannerRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> BEACON = of(BeaconRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> BELL = of(BellRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> BLOCK_ENTITY_WITH_BOUNDING_BOX = of(BlockEntityWithBoundingBoxRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> BRUSHABLE_BLOCK = of(BrushableBlockRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> CAMPFIRE = of(CampfireRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> CHEST = of(ChestRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> CONDUIT = of(ConduitRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> COPPER_GOLEM_STATUE_BLOCK = of(CopperGolemStatueBlockRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> DECORATED_POT = of(DecoratedPotRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> ENCHANT_TABLE = of(EnchantTableRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> HANGING_SIGN = of(HangingSignRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> LECTERN = of(LecternRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> PISTON_HEAD = of(PistonHeadRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> SHELF = of(ShelfRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> SHULKER_BOX = of(ShulkerBoxRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> SKULL_BLOCK = of(SkullBlockRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> SPAWNER = of(SpawnerRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> STANDING_SIGN = of(StandingSignRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> TEST_INSTANCE = of(TestInstanceRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> THE_END_GATEWAY = of(TheEndGatewayRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> THE_END_PORTAL = of(TheEndPortalRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> TRIAL_SPAWNER = of(TrialSpawnerRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> VAULT = of(VaultRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ALLAY = of(AllayRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ARMADILLO = of(ArmadilloRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ARMOR_STAND = of(ArmorStandRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> AXOLOTL = of(AxolotlRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> BAT = of(BatRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> BEE = of(BeeRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> BLAZE = of(BlazeRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> BOAT = withModel(BoatRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> BOGGED = of(BoggedRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> BREEZE = of(BreezeRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> CAMEL_HUSK = of(CamelHuskRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> CAMEL = of(CamelRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> CAT = of(CatRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> CAVE_SPIDER = of(CaveSpiderRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> CHICKEN = of(ChickenRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> COD = of(CodRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> COPPER_GOLEM = of(CopperGolemRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> COW = of(CowRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> CREAKING = of((EntityRendererProvider<Creaking>) CreakingRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> CREEPER = of(CreeperRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> DOLPHIN = of(DolphinRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> DONKEY = of(DonkeyRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> DRAGON_FIREBALL = of(DragonFireballRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> DROWNED = of(DrownedRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ELDER_GUARDIAN = of(ElderGuardianRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> END_CRYSTAL = of(EndCrystalRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ENDER_DRAGON = of(EnderDragonRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ENDERMAN = of(EndermanRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ENDERMITE = of(EndermiteRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> EVOKER_FANGS = of(EvokerFangsRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> EVOKER = of((EntityRendererProvider<SpellcasterIllager>) EvokerRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> EXPERIENCE_ORB = of(ExperienceOrbRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> FALLING_BLOCK = of(FallingBlockRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> FIREWORK_ENTITY = of(FireworkEntityRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> FISHING_HOOK = of(FishingHookRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> FOX = of(FoxRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> FROG = of(FrogRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> GHAST = of(GhastRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> GIANT_MOB = of(GiantMobRenderer::new, Codec.FLOAT.fieldOf("scale"));
//    public static final MapCodec<? extends EntityRendererProvider<?>> GLOW_SQUID = of(GlowSquidRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> GOAT = of(GoatRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> GUARDIAN = of(GuardianRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> HAPPY_GHAST = of(HappyGhastRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> HOGLIN = of(HoglinRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> HORSE = of(HorseRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> HUSK = of(HuskRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ILLUSIONER = of(IllusionerRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> IRON_GOLEM = of(IronGolemRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ITEM_ENTITY = of(ItemEntityRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ITEM_FRAME = of(ItemFrameRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> LEASH_KNOT = of(LeashKnotRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> LIGHTNING_BOLT = of(LightningBoltRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> LLAMA = of(LlamaRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> LLAMA_SPIT = of(LlamaSpitRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> MAGMA_CUBE = of(MagmaCubeRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> MINECART = withModel(MinecartRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> MUSHROOM_COW = of(MushroomCowRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> NAUTILUS = of(NautilusRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> NOOP = of(NoopRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> OCELOT = of(OcelotRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> OMINOUS_ITEM_SPAWNER = of(OminousItemSpawnerRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> PAINTING = of(PaintingRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> PANDA = of(PandaRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> PARCHED = of(ParchedRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> PARROT = of(ParrotRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> PHANTOM = of(PhantomRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> PIGLIN = of(PiglinRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> PIG = of(PigRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> PILLAGER = of(PillagerRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> POLAR_BEAR = of(PolarBearRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> PUFFERFISH = of(PufferfishRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> RABBIT = of(RabbitRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> RAFT = withModel(RaftRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> RAVAGER = of(RavagerRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SALMON = of(SalmonRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SHEEP = of(SheepRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SHULKER_BULLET = of(ShulkerBulletRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SHULKER = of(ShulkerRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SILVERFISH = of(SilverfishRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SKELETON = of(SkeletonRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SLIME = of(SlimeRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SNIFFER = of(SnifferRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SNOW_GOLEM = of(SnowGolemRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SPECTRAL_ARROW = of(SpectralArrowRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SPIDER = of(SpiderRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> SQUID = of(SquidRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> STRAY = of(StrayRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> STRIDER = of(StriderRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> SULFUR_CUBE = of(SulfurCubeRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> TADPOLE = of(TadpoleRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> THROWN_ITEM = of(ThrownItemRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> THROWN_TRIDENT = of(ThrownTridentRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> TIPPABLE_ARROW = of(TippableArrowRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> TNT_MINECART = of(TntMinecartRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> TNT = of(TntRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> TROPICAL_FISH = of(TropicalFishRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> TURTLE = of(TurtleRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> UNDEAD_HORSE = of(UndeadHorseRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> VEX = of(VexRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> VILLAGER = of(VillagerRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> VINDICATOR = of(VindicatorRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> WANDERING_TRADER = of(WanderingTraderRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> WARDEN = of(WardenRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> WIND_CHARGE = of(WindChargeRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> WITCH = of(WitchRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> WITHER_BOSS = of(WitherBossRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> WITHER_SKELETON = of(WitherSkeletonRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> WITHER_SKULL = of(WitherSkullRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> WOLF = of(WolfRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ZOGLIN = of(ZoglinRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ZOMBIE_NAUTILUS = of(ZombieNautilusRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ZOMBIE = of(ZombieRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> ZOMBIE_VILLAGER = of(ZombieVillagerRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> ZOMBIFIED_PIGLIN = of(ZombifiedPiglinRenderer::new);
//    public static final MapCodec<? extends EntityRendererProvider<?>> EQUIPMENT_LAYER = withModel(EquipmentLayerRenderer::new);
    public static final MapCodec<? extends EntityRendererProvider<?>> AVATAR = of(AvatarRenderer::new, Codec.BOOL.fieldOf("slim"));

    private static boolean bootStrap;

    public static void bootStrap() {
        if (bootStrap) return;
        bootStrap = true;
//        register(Identifier.withDefaultNamespace("banner"), BANNER);
//        register(Identifier.withDefaultNamespace("beacon"), BEACON);
//        register(Identifier.withDefaultNamespace("bell"), BELL);
//        register(Identifier.withDefaultNamespace("block_entity_with_bounding_box"), BLOCK_ENTITY_WITH_BOUNDING_BOX);
//        register(Identifier.withDefaultNamespace("brushable_block"), BRUSHABLE_BLOCK);
//        register(Identifier.withDefaultNamespace("campfire"), CAMPFIRE);
//        register(Identifier.withDefaultNamespace("chest"), CHEST);
//        register(Identifier.withDefaultNamespace("conduit"), CONDUIT);
//        register(Identifier.withDefaultNamespace("copper_golem_statue_block"), COPPER_GOLEM_STATUE_BLOCK);
//        register(Identifier.withDefaultNamespace("decorated_pot"), DECORATED_POT);
//        register(Identifier.withDefaultNamespace("enchant_table"), ENCHANT_TABLE);
//        register(Identifier.withDefaultNamespace("hanging_sign"), HANGING_SIGN);
//        register(Identifier.withDefaultNamespace("lectern"), LECTERN);
//        register(Identifier.withDefaultNamespace("piston_head"), PISTON_HEAD);
//        register(Identifier.withDefaultNamespace("shelf"), SHELF);
//        register(Identifier.withDefaultNamespace("shulker_box"), SHULKER_BOX);
//        register(Identifier.withDefaultNamespace("skull_block"), SKULL_BLOCK);
//        register(Identifier.withDefaultNamespace("spawner"), SPAWNER);
//        register(Identifier.withDefaultNamespace("standing_sign"), STANDING_SIGN);
//        register(Identifier.withDefaultNamespace("test_instance"), TEST_INSTANCE);
//        register(Identifier.withDefaultNamespace("the_end_gateway"), THE_END_GATEWAY);
//        register(Identifier.withDefaultNamespace("the_end_portal"), THE_END_PORTAL);
//        register(Identifier.withDefaultNamespace("trial_spawner"), TRIAL_SPAWNER);
//        register(Identifier.withDefaultNamespace("vault"), VAULT);
        register(Identifier.withDefaultNamespace("allay"), ALLAY);
        register(Identifier.withDefaultNamespace("armadillo"), ARMADILLO);
        register(Identifier.withDefaultNamespace("armor_stand"), ARMOR_STAND);
        register(Identifier.withDefaultNamespace("axolotl"), AXOLOTL);
        register(Identifier.withDefaultNamespace("bat"), BAT);
        register(Identifier.withDefaultNamespace("bee"), BEE);
        register(Identifier.withDefaultNamespace("blaze"), BLAZE);
        register(Identifier.withDefaultNamespace("boat"), BOAT);
        register(Identifier.withDefaultNamespace("bogged"), BOGGED);
        register(Identifier.withDefaultNamespace("breeze"), BREEZE);
        register(Identifier.withDefaultNamespace("camel_husk"), CAMEL_HUSK);
        register(Identifier.withDefaultNamespace("camel"), CAMEL);
        register(Identifier.withDefaultNamespace("cat"), CAT);
        register(Identifier.withDefaultNamespace("cave_spider"), CAVE_SPIDER);
        register(Identifier.withDefaultNamespace("chicken"), CHICKEN);
        register(Identifier.withDefaultNamespace("cod"), COD);
        register(Identifier.withDefaultNamespace("copper_golem"), COPPER_GOLEM);
        register(Identifier.withDefaultNamespace("cow"), COW);
        register(Identifier.withDefaultNamespace("creaking"), CREAKING);
        register(Identifier.withDefaultNamespace("creeper"), CREEPER);
        register(Identifier.withDefaultNamespace("dolphin"), DOLPHIN);
//        register(Identifier.withDefaultNamespace("donkey"), DONKEY);
        register(Identifier.withDefaultNamespace("dragon_fireball"), DRAGON_FIREBALL);
        register(Identifier.withDefaultNamespace("drowned"), DROWNED);
        register(Identifier.withDefaultNamespace("elder_guardian"), ELDER_GUARDIAN);
        register(Identifier.withDefaultNamespace("end_crystal"), END_CRYSTAL);
        register(Identifier.withDefaultNamespace("ender_dragon"), ENDER_DRAGON);
        register(Identifier.withDefaultNamespace("enderman"), ENDERMAN);
        register(Identifier.withDefaultNamespace("endermite"), ENDERMITE);
        register(Identifier.withDefaultNamespace("evoker_fangs"), EVOKER_FANGS);
        register(Identifier.withDefaultNamespace("evoker"), EVOKER);
        register(Identifier.withDefaultNamespace("experience_orb"), EXPERIENCE_ORB);
        register(Identifier.withDefaultNamespace("falling_block"), FALLING_BLOCK);
        register(Identifier.withDefaultNamespace("firework_entity"), FIREWORK_ENTITY);
        register(Identifier.withDefaultNamespace("fishing_hook"), FISHING_HOOK);
        register(Identifier.withDefaultNamespace("fox"), FOX);
        register(Identifier.withDefaultNamespace("frog"), FROG);
        register(Identifier.withDefaultNamespace("ghast"), GHAST);
        register(Identifier.withDefaultNamespace("giant_mob"), GIANT_MOB);
//        register(Identifier.withDefaultNamespace("glow_squid"), GLOW_SQUID);
        register(Identifier.withDefaultNamespace("goat"), GOAT);
        register(Identifier.withDefaultNamespace("guardian"), GUARDIAN);
        register(Identifier.withDefaultNamespace("happy_ghast"), HAPPY_GHAST);
        register(Identifier.withDefaultNamespace("hoglin"), HOGLIN);
        register(Identifier.withDefaultNamespace("horse"), HORSE);
        register(Identifier.withDefaultNamespace("husk"), HUSK);
        register(Identifier.withDefaultNamespace("illusioner"), ILLUSIONER);
        register(Identifier.withDefaultNamespace("iron_golem"), IRON_GOLEM);
        register(Identifier.withDefaultNamespace("item_entity"), ITEM_ENTITY);
        register(Identifier.withDefaultNamespace("item_frame"), ITEM_FRAME);
        register(Identifier.withDefaultNamespace("leash_knot"), LEASH_KNOT);
        register(Identifier.withDefaultNamespace("lightning_bolt"), LIGHTNING_BOLT);
//        register(Identifier.withDefaultNamespace("llama"), LLAMA);
        register(Identifier.withDefaultNamespace("llama_spit"), LLAMA_SPIT);
        register(Identifier.withDefaultNamespace("magma_cube"), MAGMA_CUBE);
        register(Identifier.withDefaultNamespace("minecart"), MINECART);
        register(Identifier.withDefaultNamespace("mushroom_cow"), MUSHROOM_COW);
        register(Identifier.withDefaultNamespace("nautilus"), NAUTILUS);
        register(Identifier.withDefaultNamespace("noop"), NOOP);
        register(Identifier.withDefaultNamespace("ocelot"), OCELOT);
//        register(Identifier.withDefaultNamespace("ominous_item_spawner"), OMINOUS_ITEM_SPAWNER);
        register(Identifier.withDefaultNamespace("painting"), PAINTING);
        register(Identifier.withDefaultNamespace("panda"), PANDA);
        register(Identifier.withDefaultNamespace("parched"), PARCHED);
        register(Identifier.withDefaultNamespace("parrot"), PARROT);
        register(Identifier.withDefaultNamespace("phantom"), PHANTOM);
//        register(Identifier.withDefaultNamespace("piglin"), PIGLIN);
        register(Identifier.withDefaultNamespace("pig"), PIG);
        register(Identifier.withDefaultNamespace("pillager"), PILLAGER);
        register(Identifier.withDefaultNamespace("polar_bear"), POLAR_BEAR);
        register(Identifier.withDefaultNamespace("pufferfish"), PUFFERFISH);
        register(Identifier.withDefaultNamespace("rabbit"), RABBIT);
        register(Identifier.withDefaultNamespace("raft"), RAFT);
        register(Identifier.withDefaultNamespace("ravager"), RAVAGER);
        register(Identifier.withDefaultNamespace("salmon"), SALMON);
        register(Identifier.withDefaultNamespace("sheep"), SHEEP);
        register(Identifier.withDefaultNamespace("shulker_bullet"), SHULKER_BULLET);
        register(Identifier.withDefaultNamespace("shulker"), SHULKER);
        register(Identifier.withDefaultNamespace("silverfish"), SILVERFISH);
        register(Identifier.withDefaultNamespace("skeleton"), SKELETON);
        register(Identifier.withDefaultNamespace("slime"), SLIME);
        register(Identifier.withDefaultNamespace("sniffer"), SNIFFER);
        register(Identifier.withDefaultNamespace("snow_golem"), SNOW_GOLEM);
        register(Identifier.withDefaultNamespace("spectral_arrow"), SPECTRAL_ARROW);
        register(Identifier.withDefaultNamespace("spider"), SPIDER);
//        register(Identifier.withDefaultNamespace("squid"), SQUID);
        register(Identifier.withDefaultNamespace("stray"), STRAY);
        register(Identifier.withDefaultNamespace("strider"), STRIDER);
        register(Identifier.withDefaultNamespace("sulfur_cube"), SULFUR_CUBE);
        register(Identifier.withDefaultNamespace("tadpole"), TADPOLE);
        register(Identifier.withDefaultNamespace("thrown_item"), THROWN_ITEM);
        register(Identifier.withDefaultNamespace("thrown_trident"), THROWN_TRIDENT);
        register(Identifier.withDefaultNamespace("tippable_arrow"), TIPPABLE_ARROW);
        register(Identifier.withDefaultNamespace("tnt_minecart"), TNT_MINECART);
        register(Identifier.withDefaultNamespace("tnt"), TNT);
        register(Identifier.withDefaultNamespace("tropical_fish"), TROPICAL_FISH);
        register(Identifier.withDefaultNamespace("turtle"), TURTLE);
//        register(Identifier.withDefaultNamespace("undead_horse"), UNDEAD_HORSE);
        register(Identifier.withDefaultNamespace("vex"), VEX);
        register(Identifier.withDefaultNamespace("villager"), VILLAGER);
        register(Identifier.withDefaultNamespace("vindicator"), VINDICATOR);
        register(Identifier.withDefaultNamespace("wandering_trader"), WANDERING_TRADER);
        register(Identifier.withDefaultNamespace("warden"), WARDEN);
        register(Identifier.withDefaultNamespace("wind_charge"), WIND_CHARGE);
        register(Identifier.withDefaultNamespace("witch"), WITCH);
        register(Identifier.withDefaultNamespace("wither_boss"), WITHER_BOSS);
        register(Identifier.withDefaultNamespace("wither_skeleton"), WITHER_SKELETON);
        register(Identifier.withDefaultNamespace("wither_skull"), WITHER_SKULL);
        register(Identifier.withDefaultNamespace("wolf"), WOLF);
        register(Identifier.withDefaultNamespace("zoglin"), ZOGLIN);
        register(Identifier.withDefaultNamespace("zombie_nautilus"), ZOMBIE_NAUTILUS);
        register(Identifier.withDefaultNamespace("zombie"), ZOMBIE);
        register(Identifier.withDefaultNamespace("zombie_villager"), ZOMBIE_VILLAGER);
//        register(Identifier.withDefaultNamespace("zombified_piglin"), ZOMBIFIED_PIGLIN);
//        register(Identifier.withDefaultNamespace("equipment_layer"), EQUIPMENT_LAYER);
        register(Identifier.withDefaultNamespace("avatar"), AVATAR);
    }

    public static <T extends Entity> MapCodec<? extends EntityRendererProvider<T>> of(EntityRendererProvider<T> provider) {
        return MapCodec.unit(provider);
    }

    public static <T extends Entity, S extends EntityRenderState> MapCodec<? extends EntityRendererProvider<T>> of(Supplier<EntityRenderer<T, S>> supplier) {
        return MapCodec.unit(context -> supplier.get());
    }

    public static <T extends Entity, S extends EntityRenderState, U> MapCodec<? extends EntityRendererProvider<T>> of(BiFunction<EntityRendererProvider.Context, U, EntityRenderer<T, S>> provider, MapDecoder<U> additional) {
        return CodecUtil.unilateralMap(additional.map(value -> (context -> provider.apply(context, value))));
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    public static <T extends Entity, S extends EntityRenderState> MapCodec<? extends EntityRendererProvider<T>> withModel(BiFunction<EntityRendererProvider.Context, ModelLayerLocation, EntityRenderer<T, S>> provider) {
        return CodecUtil.unilateralMap(MODEL_LAYER_LOCATION_CODEC.fieldOf("model")
                .map(modelId -> (EntityRendererProvider) (context -> provider.apply(context, modelId))));
    }

    public static void register(Identifier id, MapCodec<? extends EntityRendererProvider<?>> entry) {
        ID_MAPPER.put(id, entry);
    }
}
